name: KiCAD Exports

on:
  push:
    paths:
    - '.github/workflows/first-fab-exports.yml'
    - '02xsbcfirst/**.sch'
    - '02xsbcfirst/**.kicad_pcb'
  pull_request:
    paths:
      - '02xsbcfirst/**.sch'
      - '02xsbcfirst/**.kicad_pcb'

jobs:
  exports:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: nerdyscout/kicad-exports@v2.3.1
      name: export schematics
      with:
        config: /opt/kibot/config/docs.schema.kibot.yaml
        dir: docs
        schema: '02xsbcfirst/be6502x.sch'
        board: '02xsbcfirst/be6502x.kicad_pcb'
        verbose: 0
    - uses: nerdyscout/kicad-exports@v2.3.1
      name: export iBOM
      with:
        config: /opt/kibot/config/bom.ibom.kibot.yaml
        dir: docs
        schema: '02xsbcfirst/be6502x.sch'
        board: '02xsbcfirst/be6502x.kicad_pcb'
        verbose: 0
    - uses: nerdyscout/kicad-exports@v2.3.1
      name: export drill files
      with:
        config: /opt/kibot/config/gerbers.drills.kibot.yaml
        dir: docs
        schema: '02xsbcfirst/be6502x.sch'
        board: '02xsbcfirst/be6502x.kicad_pcb'
        verbose: 0
    - uses: nerdyscout/kicad-exports@v2.3.1
      name: export Fab files
      with:
        config: /opt/kibot/config/gerbers.kibot.yaml
        dir: docs
        schema: '02xsbcfirst/be6502x.sch'
        board: '02xsbcfirst/be6502x.kicad_pcb'
        verbose: 0
    - uses: nerdyscout/kicad-exports@v2.3.1
      name: export Board files
      with:
        config: /opt/kibot/config/docs.board.kibot.yaml	
        dir: docs
        schema: '02xsbcfirst/be6502x.sch'
        board: '02xsbcfirst/be6502x.kicad_pcb'
        verbose: 0
    - uses: nerdyscout/kicad-exports@v2.3.1
      name: zip Fab files
      with:
        config: /opt/kibot/config/compress.fabrications.kibot.yaml
        dir: docs
        schema: '02xsbcfirst/be6502x.sch'
        board: '02xsbcfirst/be6502x.kicad_pcb'
        verbose: 0
    - name: upload results
      uses: actions/upload-artifact@v2
      with:
        name: docs
        path: docs
