name: example

on:
  push:
    paths:
    - '.github/workflows/first-fab-exports.yml'
    - '02xsbcfirst/**.sch'
    - '02xsbcfirst/**.kicad_pcb'
  pull_request:
    paths:
      - '02xsbcfirst/**.sch'
      - '02xsbcfirst/**.kicad_pcb'

jobs:
  example:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: nerdyscout/kicad-exports@v2.3.1
      with:
      # Required - kibot config file
        config: /opt/kibot/config/compress.documentation.kibot.yaml
      # optional - prefix to output defined in config
        dir: docs
      # optional - schematic file
        schema: '02xsbcfirst/**.sch'
      # optional - PCB design file
        board: '02xsbcfirst/**.kicad_pcb'
      # optional - verbose output info
        verbose: 0
    - name: upload results
      uses: actions/upload-artifact@v2
      with:
        name: docs
        path: docs
